server:
  port: 8888
  
spring:
  application:
    name: CONFIG-SERVER
  sleuth:
    config:
      server:
        enabled: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kuber62/config-server.git
          clone-on-start: true
          default-label: master
          basedir: /config
               
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

unik:
  service:
    log:
      name: spring-cloud-config-server
---
spring:
  config:
    activate:
      on-profile: docker
  application:
    name: CONFIG-SERVER
  zipkin:
    base-url: http://zipkin-server:9411/
  sleuth:
    config:
      server:
        enabled: true
  cloud:
    config:
      server:
        git:
          uri: git@github.com:kuber62/config-server.git
          clone-on-start: true
          default-label: master
          basedir: /config
          force-pull: true
          strictHostKeyChecking: false

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service-registry:8761/eureka/

unik:
  service:
    log:
      name: spring-cloud-config-server