feign:
  compression:
    response:
      enabled: true
  circuitBreaker:
    enabled: true

server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8999
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    feign:
      enabled: true
  activemq:
    broker-url: tcp://localhost:61616
    packages.trust-all: true

unik:
  service:
    log:
      name: user-service
  jms-broker:
    in-queue: ${spring.application.name}-IN
    out-queue: PERSISTOR-SERVICE-IN

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  config: http://localhost:8999/config-server/default/master/logback-spring.xml
---
spring:
  profiles: docker
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://cloud-config:8999
    use-legacy-processing: true
  zipkin:
    base-url: http://zipkin-server:9411/
  sleuth:
    messaging:
      rabbit:
        enabled: true
    feign:
      enabled: true
  activemq:
    broker-url: tcp://jms-broker:61616
    packages.trust-all: true

unik:
  service:
    log:
      name: user-service
  jms-broker:
    in-queue: ${spring.application.name}-IN
    out-queue: PERSISTOR-SERVICE-IN

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service-registry:8761/eureka/

feign:
  compression:
    response:
      enabled: true
  circuitBreaker:
    enabled: true

server:
  port: 9002

logging:
  config: http://cloud-config:8999/config-server/docker/master/logback-spring.xml